version: "3.3"
services:
  yarn:
    stdin_open: true
    tty: true
    volumes:
      - ./:/app
    build:
      context: .
      dockerfile: ./yarn.dockerfile
      # dockerfile: ./dockerfiles/yarn.dockerfile
